on: [pull_request]

name: PR Validator

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test
